name: Publish Website
on:
   push:
    branches:
     - master 
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    env:
       DB_HOST: 15.184.104.36
       DB_DATABASE: ladyes
       DB_USERNAME: ladyes
       DB_PASSWORD: eN7]CO@0eBriN1fL
       BROADCAST_DRIVER: log
    services:
           mysql:
            image: mysql:5.7
            env:
                MYSQL_ALLOW_EMPTY_PASSWORD: false
                MYSQL_ROOT_PASSWORD: eN7]CO@0eBriN1fL
                MYSQL_DATABASE: ladyes
            ports:
                   - 3306/tcp
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
         php-version: "8.0.1"
         extensions: mbstring, dom, fileinfo, mysql
    - name: Verify PHP version
      run: php -v
    - name: Enable Debug Logging
      run: |
        echo "Debugging..."
        php -i
         php -m
    - name: Get composer cache directory 
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
           path: ${{ steps.composer-cache.outputs.dir }}
           key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
           restore-keys: ${{ runner.os }}-composer-
    - name: Install Composer dependencies
      run: composer update 
    - name: Storage link
      run: php artisan storage:link 
    - name: run migration
      run: php artisan migrate --force  
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
         log-level: verbose
         server: 15.184.104.36
         server-dir: public_html
         username: ubuntu
         password: RHGVYTrf#ghfgyf43453
         exclude: |
            **/node_modules/**
    
    
