name: Publish Website
on:
   push:
    branches:
     - master 
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    env:
       DB_HOST: app.ladyes.co
       DB_DATABASE: appladyes0_mnjz
       DB_USERNAME: appladyes0_mnjz
       DB_PASSWORD: M*5V{]pm#+$N
       BROADCAST_DRIVER: log
    services:
           mysql:
            image: mysql:8
            env:
                MYSQL_ALLOW_EMPTY_PASSWORD: false
                MYSQL_ROOT_PASSWORD: M*5V{]pm#+$N
                MYSQL_DATABASE: appladyes0_mnjz
            ports:
                   - 3306/tcp
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
         php-version: "8.0"
         extensions: mbstring, dom, fileinfo, mysql
    - name: Start mysql service
      run: sudo /etc/init.d/mysql start 
    - name: Get composer cache directory 
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
           path: ${{ steps.composer-cache.outputs.dir }}
           key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
           restore-keys: ${{ runner.os }}-composer-
    - name: Install Composer dependencies
      run: composer update 
    - name: Storage link
      run: php artisan storage:link 
    - name: run migration
      run: php artisan migrate --force  
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
         log-level: verbose
         server: app.ladyes.co
         server-dir: public_html
         username: appladyes0
         password: Aa@112223344@aA
         exclude: |
            **/node_modules/**
    
    
